version: '3.8'

services:
  bot:
    build: .
    container_name: audio_bot
    restart: unless-stopped
    environment:
      TZ: Europe/Moscow
    env_file:
      - .env
    volumes:
      - ./bot:/app/bot                          # монтируем весь код бота
      - ./bot/audio_files:/app/bot/audio_files  # уже было
      - ./logs:/app/logs                        # уже было
      - ./init_data.py:/app/init_data.py        # скрипт инициализации данных
    depends_on:
      - db
    networks:
      - bot_network

  db:
    image: postgres:15-alpine
    container_name: audio_bot_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=ru_RU.UTF-8"
      TZ: Europe/Moscow
      PGTZ: Europe/Moscow
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bot_network
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: audio_bot_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - bot_network
    depends_on:
      - db

  web-converter:
    build:
      context: .
      dockerfile: web-converter/Dockerfile
    container_name: audio_converter
    restart: unless-stopped
    environment:
      TZ: Europe/Moscow
    env_file:
      - .env
    ports:
      - "1992:1992"
    volumes:
      - ./bot/utils:/app/bot/utils                    # переиспользуем FFmpeg утилиты
      - ./web-converter:/app/web-converter            # монтируем код веб-сервиса
    networks:
      - bot_network

volumes:
  postgres_data:

networks:
  bot_network:
    driver: bridge